package endpass.android.endpass_sdk.presentation.impl




interface VerifyFragmentStrategy {

    fun desc(): String

    fun resentDesc(): String

    fun errorMsg(): String

    fun isLineVisibilty(): Boolean = false

}


class OtpCodeStrategy : VerifyFragmentStrategy {

    override fun resentDesc(): String = "DON\'T KNOW THE CODE?"

    override fun desc(): String  = "Enter the 6 digit code generated by your authenticator app.."

    override fun errorMsg(): String = "user does not have verified phones"

}


class EmailCodeStrategy : VerifyFragmentStrategy {

    override fun resentDesc(): String = "DIDN\'T GET THE CODE?"

    override fun desc(): String  = "We just sent a six-digit code to your mail.\nEnter the code you received."

    override fun errorMsg(): String = "find code by user: Not found"

}


class RecoverCodeStrategy : VerifyFragmentStrategy {

    override fun resentDesc(): String = "DIDN\'T GET THE CODE?"

    override fun desc(): String  = "We  sent a code to your phone number.\nEnter the code you received."

    override fun errorMsg(): String = "find code by user: Not found"

    override fun isLineVisibilty(): Boolean = true

}


class RecoverConfirmStrategy : VerifyFragmentStrategy {

    override fun resentDesc(): String = "DIDN\'T GET THE CODE?"

    override fun desc(): String  = "We just sent a six-digit code to your mail.\nEnter the code you received."

    override fun errorMsg(): String = "find code by user: Not found"

    override fun isLineVisibilty(): Boolean = true

}


class RemoveDocumentStrategy : VerifyFragmentStrategy {

    override fun resentDesc(): String = "DIDN\'T GET THE CODE?"

    override fun desc(): String  = "Please enter the code which we sent to your email address\n"

    override fun errorMsg(): String = "temp code mismatch"

    override fun isLineVisibilty(): Boolean = true

}
class OauthStrategy : VerifyFragmentStrategy {

    override fun resentDesc(): String = "DIDN\'T GET THE CODE?"

    override fun desc(): String  = "Please enter the code which we sent to your email address\n"

    override fun errorMsg(): String = "temp code mismatch"

    override fun isLineVisibilty(): Boolean = true

}